[pytest]
addopts = --basetemp=.pytest_temp -p no:cacheprovider
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:starlette\..*
    ignore::DeprecationWarning:passlib\..*
    ignore::DeprecationWarning:sqlalchemy\..*
